services:
<<<<<<< HEAD
=======
  db:
    image: postgres:16
    ports:
      - "7070:5432"
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: stardust
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
>>>>>>> e3c4ef103c266fea3efc4f4fe26f2be72546600c
  app:
    build: .
    ports:
      - "7071:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://xo.zipcode.rocks:9088/circus"
      SPRING_DATASOURCE_USERNAME: sunflower_user
      SPRING_DATASOURCE_PASSWORD: zipmusic
