spring.datasource.url=jdbc:postgresql://xo.zipcode.rocks:9088/circus
spring.datasource.username=sunflower_user
spring.datasource.password=zipmusic
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=7071
spring.application.name=Schooner
site.name=Schooner
site.description=a schooner forum
spring.thymeleaf.cache=false
